---
- name: Provision EC2 instance
  hosts: localhost
  gather_facts: false
  vars:
    instance_type: t2.micro
    ami: ami-0c94855ba95c71c99 #id da imagem da AWS que deseja usar
    key_name: aws_key
    region: us-east-1
    security_group: sg-12345678 #id do grupo de segurança
  tasks:
  - name: Launch EC2 Instance
    ec2:
      region: "{{ region }}"
      image: "{{ ami }}"
      instance_type: "{{ instance_type }}"
      key_name: "{{ key_name }}"
      group_id: "{{ security_group }}"
      wait: true
      count: 1
    register: ec2

  - name: Add new instance to host group
    add_host:
      hostname: "{{ ec2.instances[0].public_dns_name }}"
      groups: launched

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ ec2.instances[0].public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started

  - name: Update the package cache on the new instance
    become: true
    become_user: ec2-user
    yum:
      name: '*'
      state: latest
